name: goreleaser

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      -
        name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: UPX version
        run: upx --version

      -
        name: "Create release on GitHub"
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: "release --clean --debug -f .github/conf/.goreleaser.yml"
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
